### ISSUE TITLE
Adobe NotDef?

### ISSUE THREAD

**Issue by davelab6** [adobe-fonts/adobe-blank#5]
I think it could be useful to have an "Adobe NotDef" font, that is similar except there is 1 glyph with the standard notdef design, so that fonts that use non-standard notdefs could be avoided by placing it at the end of the font stack.

**Comment by kenlunde** [comment]
AND-Regular 🤔

**Comment by kenlunde** [comment]
Launched just now → https://github.com/adobe-fonts/adobe-notdef/

**Comment by davelab6** [comment]
🙌

**Comment by kenlunde** [comment]
And, it includes "-Regular" in its PostScript name. 😉

**Comment by davelab6** [comment]
lol ken! Thank you!!!! :D

**Comment by davelab6** [comment]
Office comment: "Wow that was quick"

**Comment by kenlunde** [comment]
From start to finish, including the push to GitHub, the entire process took approximately 30 minutes. I repurposed much of Adobe Blank, such as using the same UTF-32 CMap resource, and effectively changed only the glyphs. I deployed only the OpenType/CFF flavor, and will consider adding other formats, such as the ones included with Adobe Blank, if demand suggests doing so.
