### ISSUE TITLE
Webfont serving?

### ISSUE THREAD

**Issue by behdad** [adobe-fonts/adobe-blank#7]
Is it possible to setup https://adobe-fonts.github.io/adobe-blank to allow serving webfonts directly from github? Thanks.

**Comment by punchcutter** [comment]
Did you want something in particular? And you specifically want the static and not the VFs from https://github.com/adobe-fonts/adobe-blank-vf?

**Comment by behdad** [comment]
Ah I didn't know about the VF. At any rate, Dave pointed out that the Google Fonts service already serves this font, it's just not listed in the directory. So my need (using Adobe Blank from codepen.io) is satisfied. Closing. Maybe worth adding to the documentation.
